### ISSUE TITLE
Adapters and Plugins

### ISSUE THREAD

**Issue by mikepianka** [Elius94/react-photo-sphere-viewer#1]
Nice work on this! I was actually going down the same path of trying to get PSV working nicely in React and just happened to find this because I had coincidentally named a repo with the same name. 

I'm not sure if this is implemented, but how would you go about using an adapter or plugin. Like the [compass plugin](https://photo-sphere-viewer.js.org/plugins/plugin-compass.html#usage)? I see that there is a plugins prop but not sure what your preferred method would be for bringing in `CompassPlugin`. Thanks!

**Comment by Elius94** [comment]
Hi mike, thanks a lot, it's a pleasure for me!
I didn't tried to add another plugin yet, but in the options that I've exposed it's possible to pass the plugins array:
https://github.com/Elius94/react-photo-sphere-viewer/blob/fa21882e71c1bd5a0e7269f2e6c6921a1253485e/src/index.tsx#L106

If you want you can try to add it to the PSV instance and let me know.

Any improvements is well accepted to this repo!
Let me know.

**Comment by mikepianka** [comment]
Yeah I tried but was hitting the same issue that I was before I discovered your project. Also just FYI I had to `ts-ignore` the height and width because it wants a number but I was trying to pass in a viewport string like you did in your example.

For example, this:
```js
// App.tsx

import "./App.css";
import ReactPhotoSphereViewer from "react-photo-sphere-viewer";
import { CompassPlugin } from "photo-sphere-viewer/dist/plugins/compass";

function App() {
  return (
    <div className="App">
      <ReactPhotoSphereViewer
        src="assets/pano.jpg"
        // @ts-ignore
        height={"100vh"}
        // @ts-ignore
        width={"100vw"}
        plugins={[CompassPlugin]}
      />
    </div>
  );
}

export default App;
```

Causes this `THREE.Quaternion is not a constructor` error to show up due to the `CompassPlugin` import. This isn't something with your component but rather just an issue with the photo-sphere-viewer node_modules package.
![image](https://user-images.githubusercontent.com/47948499/186216313-cf8f95d2-53b6-49bc-8781-237003f2a6f9.png)

See https://github.com/mistic100/Photo-Sphere-Viewer/issues/729 and the older issue https://github.com/mistic100/Photo-Sphere-Viewer/issues/656. It doesn't seem like you are having these issues in your core library so I think it's something to do with webpack? I wonder about if you just import all the adapters and plugins to your library and then export them to make them available if it would bypass this issue.

**Comment by Elius94** [comment]
Hi, yes, I can add al the plugin into my lib and then allow the user to enable them individually.
The only thing is the eventual increase of code size. Let me try something.
Another thing is that there's a new PSV version that I need to upgrade. I will manage this and your issue in the next days.
Thanks for the help and you are welcome to contribute to this repo ☺️🙏

**Comment by mikepianka** [comment]
So I tried running the latest build from PSV's dev branch and then using that inside this repo. See https://github.com/mikepianka/react-photo-sphere-viewer/tree/plugins and the package is https://www.npmjs.com/package/@mikepianka/react-photo-sphere-viewer.

Something isn't right though because it has trouble resolving `photo-sphere-viewer` from adapters and plugins:
![image](https://user-images.githubusercontent.com/47948499/186252887-7a5858b8-f31d-4b87-8e47-c1bd5ac647f3.png)

**Comment by Elius94** [comment]
How did you point to the library? With a link to a file in the package.json?

**Comment by mikepianka** [comment]
I ran a build from PSV's dev branch and then published it to NPM. It's the @mikepianka/photo-sphere-viewer dependency.

**Comment by Elius94** [comment]
The only thing I can try to do is to pre-include the plugins.
I will let you know in the next days :D

**Comment by Elius94** [comment]
@mikepianka Thanks, I've added all the adapter and plugins to my react wrapper exports.

**Comment by mikepianka** [comment]
OK great I will check it out. I noticed that an official little planet adapter was added in v4.7.1 you might be interested in.

https://github.com/mistic100/Photo-Sphere-Viewer/releases/tag/4.7.1

https://photo-sphere-viewer.js.org/guide/adapters/little-planet.html

**Comment by Elius94** [comment]
Yes, I'm talking to its developer, who has asked me for permission to use my method to improve his. I'm in contact with him to integrate my version of Wrapper for React with his
