### ISSUE TITLE
Correct use of Gyroscope Plugin?

### ISSUE THREAD

**Issue by AidanNelson** [Elius94/react-photo-sphere-viewer#12]
Hi There,

Thanks for releasing this library.  It has been a joy to work with so far!

One issue I ran into is this: the Gyroscope plugin (which supports mobile device orientation controls) does not seem to be working as expected.  My app is building correctly, but the plugin is not visible or working on mobile.

Here is a minimal reproduction: https://codesandbox.io/s/react-photo-sphere-gyroscope-plugin-test-klupfk?file=/src/App.js

And here is my code:

```js
import React from "react";
import {
  ReactPhotoSphereViewer,
  GyroscopePlugin
} from "react-photo-sphere-viewer";

function PhotoSphere() {
  const photoSphereRef = React.useRef();

  const plugins = [GyroscopePlugin];

  return (
    <div>
      <ReactPhotoSphereViewer
        ref={photoSphereRef}
        src={"./bourke-pano.jpg"}
        height={"60vh"}
        width={"100%"}
        plugins={plugins}
      ></ReactPhotoSphereViewer>
    </div>
  );
}

export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <PhotoSphere />
    </div>
  );
}
```

The gyroscope feature should be available on mobile, but doesn't seem to be.  

Please let me know if I should be doing anything differently.

Thanks!

**Comment by Elius94** [comment]
Hello! thanks for your issue. Now I'll check this issue to figure it out

**Comment by tschmidt01** [comment]
With the current implementation, you have to provide the navbar manually, e.g. `navbar={['gyroscope']}`

**Comment by Elius94** [comment]
[![Edit react-photo-sphere-gyroscope-plugin-test (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-photo-sphere-gyroscope-plugin-test-forked-q6r0tq?fontsize=14&hidenavigation=1&theme=dark)

Ok, this is working well! I close

**Comment by Elius94** [comment]
> With the current implementation, you have to provide the navbar manually, e.g. `navbar={['gyroscope']}`

Thank you man!

**Comment by nguyenvd3** [comment]
> With the current implementation, you have to provide the navbar manually, e.g. `navbar={['gyroscope']}`

Hi @tschmidt01, i'm trying to use Stereo Plugins by this way: `navbar={['gyroscope', 'stereo']}` but it's not working, any idea for it.

**Comment by Elius94** [comment]
Hi!
[![Edit react-photo-sphere-gyroscope-plugin-test (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-photo-sphere-gyroscope-plugin-test-forked-q6r0tq?fontsize=14&hidenavigation=1&theme=dark)

This example with gyroscope and stereo is working in my Android phone

**Comment by nguyenvd3** [comment]
Thank you Elius, i checked and it worked fine on Android, but on my Iphone got the error, i guess this error is caused by some policy on Iphone.

![WhatsApp Image 2023-02-15 at 09 03 33](https://user-images.githubusercontent.com/55442292/218909780-5da5bf56-d0ee-4457-a497-fde170bcc00f.jpeg)

**Comment by Elius94** [comment]
Hi! Are you shure that you are running the last version of the library? I
remember that this was an issue in the main library, solved in the current
release.

Il mer 15 feb 2023, 03:16 nguyenvd-3 ***@***.***> ha scritto:
