### ISSUE TITLE
little planet initialize zoom

### ISSUE THREAD

**Issue by JuJinHyeong** [Elius94/react-photo-sphere-viewer#17]
Hello. Thank you for providing such a good module.

I'm using the littleplanet props, but if I don't click it when I start, I can't zoom in with scroll or initialize it. Maybe it's meant to be?

      <ReactPhotoSphereViewer
        ref={pSRef}
        src={img}
        height={'100vh'}
        width={'100%'}
        onClick={handleClick}
        onReady={handleReady}
        plugins={plugins}
        defaultZoomLvl={50}
        container={''}
        littlePlanet
        minFov={-100}
        maxFov={50}
        defaultPitch={0}
      />

**Comment by Elius94** [comment]
Hi! I'll check better when I'll be home, now I'm in holiday!
Can you explain your trouble better? maybe with a video screenshot?
But if you see in the code, using littleplanet prop, you can't set minFov and maxFov.
Thank you

**Comment by JuJinHyeong** [comment]
happy new year!
thank you for checking! and sorry for my bad english.

i start react app i can see little planet view. but when i move my mouse wheel, there is no action(zoom in/out) in scene.
and when i click scene,  zoom in and start auto scroll.
then i can zoom in/out properly.

thank you for answer set minFov and maxFov.

![Honeycam 2023-01-02 20-59-50](https://user-images.githubusercontent.com/34227015/210228561-adc11371-bc2d-45af-9939-49f9ed0ee509.gif)

**Comment by JuJinHyeong** [comment]
oh! i found it. click means little planet mode off.

i think fisheye option is my goal.

thank you for answer!

**Comment by Elius94** [comment]
Nice! Thank you
