### ISSUE TITLE
[Support]: Visible area settings.

### ISSUE THREAD

**Issue by yusufarsln98** [Elius94/react-photo-sphere-viewer#27]
### What are you trying to do?
Hello,
I have a partial panoramic photo, but there are some dark areas at the back and top of the image. Can you advise me on what settings I should use to hide them?

### Sandbox Link

https://codesandbox.io/s/partial-panorama-react-photo-sphere-viewer-z7f3mk?file=/src/App.js

### Library Version

3.3.3-psv5.1.1

### What operating system are you using?

Windows

Thank you!

**Comment by Elius94** [comment]
Hi. Your test image is 1x1, to work, the panorama must be 2x1, alternatively you should use it differently by following the main library guide. Also, your image already contains empty areas, top and bottom, and this is the reason for the black circles at the top and bottom.

**Comment by yusufarsln98** [comment]
Sir, thank you for your answers. I know that my image has empty areas. Maybe I expressed myself incorrectly. What I actually want to do is to limit the area that the user can see. For example, I want to restrict the horizontal view between -90 and 90 degrees and prevent any vertical movement. I followed the original documentation, but I could not find any guide on how to achieve this. If such a guide exists, I would appreciate it if you could please show it to me. Thank you.

**Comment by Elius94** [comment]
Hi! ok I got it. In truth I have never done this, maybe you should open an issue in the original repository of the library "photo-sphere-viewer".
good luck

**Comment by yusufarsln98** [comment]
I found [VisibleRangePlugin](https://photo-sphere-viewer.js.org/plugins/visible-range.html#usage), and it solved my problem. Thanks for being interested.
