### ISSUE TITLE
[Bug]: Error when showing multiple photospheres one one page

### ISSUE THREAD

**Issue by tap2k** [Elius94/react-photo-sphere-viewer#29]
### What happened?

When showing multiple photospheres on one page, I get the following error. Verified on Chrome and Safari, Windows and Mac. 

Unhandled Runtime Error
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-5) is negative.
Call Stack
Loader.setProgress
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (5774:0)
eval
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (2995:0)
eval
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (8299:0)
new Promise
<anonymous>
TextureLoader.loadFile
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (8297:0)
EquirectangularAdapter.__loadXMP
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (3062:0)
EquirectangularAdapter.loadTexture
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (2994:0)
Viewer.setPanorama
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (9379:0)
new Viewer
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (9097:0)
eval
node_modules/react-photo-sphere-viewer/dist/index.js (99:0)
commitHookEffectListMount
node_modules/react-dom/cjs/react-dom.development.js (23150:0)
commitPassiveMountOnFiber
node_modules/react-dom/cjs/react-dom.development.js (24926:0)
commitPassiveMountEffects_complete
node_modules/react-dom/cjs/react-dom.development.js (24891:0)
commitPassiveMountEffects_begin
node_modules/react-dom/cjs/react-dom.development.js (24878:0)
commitPassiveMountEffects
node_modules/react-dom/cjs/react-dom.development.js (24866:0)
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js (27039:0)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (26984:0)
commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js (26935:0)
commitRoot
node_modules/react-dom/cjs/react-dom.development.js (26682:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (26117:0)
flushSyncCallbacks
node_modules/react-dom/cjs/react-dom.development.js (12042:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (25651:0)

### What should have happened?

Should have show the multiple photospheres

### Library Version

latest

### What operating system are you using?

macOS

### What browser are you using?

Chrome

### Interest to fix the bug

- [ ] I would like to fix this bug!

**Comment by Elius94** [comment]
Hi! please make a sandbox and let me see what's happen.
