### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by mikepianka** [Elius94/react-photo-sphere-viewer#3]
It seems like the example app included in the repo is not working.

To reproduce:
```bash
cd .\example\
npm install
npm start
```

Results in:
![image](https://user-images.githubusercontent.com/47948499/189136854-849bcb49-2031-4fe3-9242-56bcd315e2b5.png)

I also tried modifying the _package.json_ to use the published package from the registry instead of the symbolic link to the local one, but the error still comes up.

```json
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "prop-types": "^15.5.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-photo-sphere-viewer": "^2.1.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```

**Comment by Elius94** [comment]
Hi! for me it's working. check this codesandbox:

https://codesandbox.io/s/sandbox-react-photo-sphere-viewer-by-elius94-j064sm?file=/src/App.js

Beware that if you download my repo and want to develop above, you must first "npm run start" in the root directory. Then you have to delete "React" and "React-dom" from "node-modules" (not the one from the example folder).
Then enter example and do npm install and npm run start

**Comment by mikepianka** [comment]
Ah ok, yes I was trying to work in your repo directly. I will try to delete react like you mention.

**Comment by Elius94** [comment]
Ok, so, for the moment I close the issue. Let me know if it works! thanks
