### ISSUE TITLE
[Feature]: Do you have any plan for Drag and drop functionalities? For markers and maybe a drop event on the viewer

### ISSUE THREAD

**Issue by Codename-404** [Elius94/react-photo-sphere-viewer#32]
### What do you want?

First of all, Thank you very much for this great plugin. This is very well developed and has a lot of features.

However it might be a nice to have a drag and drop feature for markers,  and maybe a drop event on the viewer.

### Why do you want it?

It would be great to be able to drag and drop points in the viewer from outside also maybe change marker position after placing.

### How do you implement it?

Only the event information would be great i believe, everything else is already setup.

Just need yaw and pitch value once an item is dropped on the viewer. 
For markers it would be great if they are draggable and share event data once drag starts and once it ends.

I selected yes, i am interested, however I might need help from you to understand how things are working right now if you want me to develop the feature.

### Are you interested in developing this feature?

- [X] Yes, I am interested in developing this feature
- [ ] No, I am not interested in developing this feature

**Comment by Elius94** [comment]
Hi! I think that this is possible using some workaround in the main library (photo-sphere-viewer)
