### ISSUE TITLE
[Support]: Using Equirectangular Video

### ISSUE THREAD

**Issue by bighamj** [Elius94/react-photo-sphere-viewer#33]
### What are you trying to do?

Trying to use this with an Equirectangular video. I had issues with PhotoSphereViewer directly, so I found this package.

Am I missing something for using it? Adding src to the component keep resulting in "Invalid panorama configuration, are you using the right adapter?"

### Code

```js
<ReactPhotoSphereViewer
  height="500px"
  width="100%"
  plugins={[[VideoPlugin]]}
  adapter={[EquirectangularVideoAdapter]}
  panorama={{
  source:
                    "my mp4 video url set by state",
  }}
  keyboardActions={true}
  keyboard={true}
></ReactPhotoSphereViewer>
```

### Library Version

^3.3.5-psv5.1.4

### What operating system are you using?

macOS

### What browser are you using?

Chrome

**Comment by Elius94** [comment]
Hi! please make me a sandbox :)

**Comment by tmj1220** [comment]
How to fix this problem
