### ISSUE TITLE
[Support]: VirtualTourPlugin

### ISSUE THREAD

**Issue by tommasocisternino** [Elius94/react-photo-sphere-viewer#36]
### What are you trying to do?

I'm tryng to use the example provided by the offical guide, but it's not working, it shows me blank screen with a label "loading" in white colored. I think there is a problem related to the src prop required in the component.
What SRC should I provide? There is an other way to do it?

[https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#example](URL TO EXAMPLE SOURCE CODE)

![image](https://github.com/Elius94/react-photo-sphere-viewer/assets/71891129/02f5ba6c-6960-4c15-a253-b0ca00eb551f)

### Code

import React, { useEffect, useState } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import useTypedPage from '@/Hooks/useTypedPage';
import GraphicLayout from '@/Layouts/GraphicLayout';

import {
  ReactPhotoSphereViewer,
  MarkersPlugin,
  VirtualTourPlugin,
} from 'react-photo-sphere-viewer';
import Utils from '../../../services/utils';

export default function MainView() {
  const page = useTypedPage();

  const pSRef = React.createRef();

  const plugins = [
    [
      VirtualTourPlugin,
      {
        positionMode: 'gps',
        renderMode: '3d',
      },
    ],
  ];

  const handleReady = instance => {
   const baseUrl = 'https://photo-sphere-viewer-data.netlify.app/assets/';
    const caption = 'Cape Florida Light, Key Biscayne <b>&copy; Pixexid</b>';

    const virtualTour = instance.getPlugin(VirtualTourPlugin);

    const markerLighthouse = {
      id: 'marker-1',
      image: baseUrl + 'pictos/pin-red.png',
      tooltip: 'Cape Florida Light, Key Biscayne',
      size: { width: 32, height: 32 },
      anchor: 'bottom center',
      gps: [-80.155973, 25.666601, 3],
    };

    virtualTour.setNodes(
      [
        {
          id: '1',
          panorama: baseUrl + 'tour/key-biscayne-1.jpg',
          thumbnail: baseUrl + 'tour/key-biscayne-1-thumb.jpg',
          name: 'One',
          caption: `[1] ${caption}`,
          links: [{ nodeId: '2' }],
          markers: [markerLighthouse],
          gps: [-80.156479, 25.666725, 3],
          panoData: { poseHeading: 180 },
        },
        {
          id: '2',
          panorama: baseUrl + 'tour/key-biscayne-2.jpg',
          thumbnail: baseUrl + 'tour/key-biscayne-2-thumb.jpg',
          name: 'Two',
          caption: `[2] ${caption}`,
          links: [{ nodeId: '3' }, { nodeId: '1' }],
          markers: [markerLighthouse],
          gps: [-80.156168, 25.666623, 3],
          panoData: { poseHeading: 318 },
        },
        {
          id: '3',
          panorama: baseUrl + 'tour/key-biscayne-3.jpg',
          thumbnail: baseUrl + 'tour/key-biscayne-3-thumb.jpg',
          name: 'Three',
          caption: `[3] ${caption}`,
          links: [{ nodeId: '4' }, { nodeId: '2' }, { nodeId: '5' }],
          gps: [-80.155932, 25.666498, 5],
          panoData: { poseHeading: 310 },
        },
        {
          id: '4',
          panorama: baseUrl + 'tour/key-biscayne-4.jpg',
          thumbnail: baseUrl + 'tour/key-biscayne-4-thumb.jpg',
          name: 'Four',
          caption: `[4] ${caption}`,
          links: [{ nodeId: '3' }, { nodeId: '5' }],
          gps: [-80.156089, 25.666357, 3],
          panoData: { poseHeading: 78 },
        },
        {
          id: '5',
          panorama: baseUrl + 'tour/key-biscayne-5.jpg',
          thumbnail: baseUrl + 'tour/key-biscayne-5-thumb.jpg',
          name: 'Five',
          caption: `[5] ${caption}`,
          links: [{ nodeId: '6' }, { nodeId: '3' }, { nodeId: '4' }],
          gps: [-80.156292, 25.666446, 2],
          panoData: { poseHeading: 190 },
        },
        {
          id: '6',
          panorama: baseUrl + 'tour/key-biscayne-6.jpg',
          thumbnail: baseUrl + 'tour/key-biscayne-6-thumb.jpg',
          name: 'Six',
          caption: `[6] ${caption}`,
          links: [{ nodeId: '5' }, { nodeId: '7' }],
          gps: [-80.156465, 25.666496, 2],
          panoData: { poseHeading: 295 },
        },
        {
          id: '7',
          panorama: baseUrl + 'tour/key-biscayne-7.jpg',
          thumbnail: baseUrl + 'tour/key-biscayne-7-thumb.jpg',
          name: 'Seven',
          caption: `[7] ${caption}`,
          links: [{ nodeId: '6' }],
          gps: [-80.15707, 25.6665, 3],
          panoData: { poseHeading: 250, posePitch: 3 },
        },
      ],
      '2',
    );
    if (!markersPlugs) return;
  };

  const handleClick = data => {
    console.log(data);
  };

  return (
    <AppLayout title={'Main Page'}>
      <GraphicLayout>
        <div
          className={'col-span-1 sm:col-span-4 md:col-span-12 my-auto py-24 '}
          id={'container-360'}
        >
          {plugins && (
            <ReactPhotoSphereViewer
              ref={pSRef}
              height={'700px'}
              width={'100%'}
              littlePlanet={false}
              onClick={handleClick}
              onReady={handleReady}
              plugins={plugins}
              container={'container-360'}
            ></ReactPhotoSphereViewer>
          )}
        </div>
      </GraphicLayout>
    </AppLayout>
  );
}

### Library Version

latest

### What operating system are you using?

Windows

### What browser are you using?

Chrome

**Comment by tommasocisternino** [comment]
If I put a placeholder image in the src prop, the VirtualTour starts working because the onReady methods handle the Virtual plugin instance and destroy the old one. I suggest to fix that by not requiring the src prop.

**Comment by Elius94** [comment]
Thanks for this issue! I've added a note in the readme to specify this.
