### ISSUE TITLE
How to use markersPlugin methods?

### ISSUE THREAD

**Issue by kalechao87** [Elius94/react-photo-sphere-viewer#4]
As official doc says, first need to get markPlugin, but useRef.current can't getPlugin

const markersPlugin = viewer.getPlugin(PhotoSphereViewer.MarkersPlugin);

how to getPlugin and use methods in react-photo-sphere-viewer?

**Comment by Elius94** [comment]
Thank you for the issue! I'm gonna find a solution! Feel free to contribute

**Comment by Elius94** [comment]
It should be fixed! New release 2.1.2 is now in uploading
