### ISSUE TITLE
VirtualTourPlugin support tiles

### ISSUE THREAD

**Issue by missBlueWhite** [Elius94/react-photo-sphere-viewer#40]
### What are you trying to do?

in VirtualTourPlugin ,i change the nodes's  panorama from string to object.  i want  VirtualTourPlugin  support tiles.
![image](https://github.com/Elius94/react-photo-sphere-viewer/assets/130877626/bcfb4a10-ef5b-4738-b0a2-7bd4e1188c34)
![image](https://github.com/Elius94/react-photo-sphere-viewer/assets/130877626/9cb6c7b4-77d1-4000-bfdf-cb53456fae63)

### Library Version

lasted

### What operating system are you using?

Windows

### What browser are you using?

None

**Comment by Elius94** [comment]
Hi, I saw that you have already added a issue to "photo-sphere-viewer". After some tests I think that it's a problem of the main lib.

**Comment by Elius94** [comment]
Please refer to: https://github.com/mistic100/Photo-Sphere-Viewer/issues/1168 issue in main lib. add the Adapter to the Viewer.
