### ISSUE TITLE
[Support]: Adding different 3D arrow models to the Virtual Tour Plugin and changing their vertical position

### ISSUE THREAD

**Issue by hakan-berat** [Elius94/react-photo-sphere-viewer#42]
### What are you trying to do?

Hi,

I am developing an web application using this library and the Virtual Tour Plugin, but I have not been able to customize the 3D arrow models and give specific values to their vertical position. Can you provide information on how I can do this?

Best Regards

### Library Version
3.4.0-psv5.4.0

### What operating system are you using?

macOS
### What browser are you using?
Chrome

**Comment by Elius94** [comment]
Hi! Thanks for your issue, but I have to close it because it's related to the main library photo-sphere-viewer by Damien Sorel. Consider to ask him on his repo.
Thanks

**Comment by mete-cozer** [comment]
Hello again

In the main library we customized the 3D arrow and put our own model and it worked very well. After forking the main library and putting the arrow we customized, we want to use the arrow we customized through this React library. How can we give a path the library we forked in this library.

**Comment by Elius94** [comment]
Hey! The only way Is to fork also my repo and use It as local lib.
Of course Is not really comfortable for the mainteinment of your project. I
suggest to make a PR on the main lib with a custom prop or method to change
the Arrow model.
This should be a nice improvement for photo-sphere-viewer.
Thanks

Il gio 28 dic 2023, 20:22 Mete Çözer ***@***.***> ha scritto:

**Comment by hakan-berat** [comment]
Hey, 

I'm sorry to have taken up your time. I don't think I'm talented enough to contribute to an open source project yet, but I will definitely try to realize this idea in the future. I'm interested in the idea of being able to fork and use both repos, would you mind explaining the milestones of this process in general?
