### ISSUE TITLE
[Feature]: Custom lang for littlePlanet button

### ISSUE THREAD

**Issue by CNFeffery** [Elius94/react-photo-sphere-viewer#43]
### What do you want?

Is there any way to custom the hover title of `littlePlanet ` button:
![image](https://github.com/Elius94/react-photo-sphere-viewer/assets/49147660/877dc8be-9682-4d78-97c2-aadcdf0a6f9e)

### Why do you want it?

use origin `lang` parameters to custom the title

### Are you interested in developing this feature?

- [ ] Yes, I am interested in developing this feature
- [X] No, I am not interested in developing this feature

**Comment by Elius94** [comment]
Hey! ok, I'll add this feature in the next release.

**Comment by Elius94** [comment]
![image](https://github.com/Elius94/react-photo-sphere-viewer/assets/14907987/df4a6068-61b1-4daf-80d1-28025f0e7ef3)

Added in the incoming release!
