### ISSUE TITLE
[Feature]: Update the readme to setup with Next.js 13-14

### ISSUE THREAD

**Issue by mkubdev** [Elius94/react-photo-sphere-viewer#54]
### What do you want?

Update the readme examples in order to work with nextjs 13/14, with [page](https://nextjs.org/docs/pages) and [app](https://nextjs.org/docs/app) router.

### Why do you want it?

Because users struggle to implement it, eg https://github.com/Elius94/react-photo-sphere-viewer/issues/51

### Are you interested in developing this feature?

- [X] Yes, I am interested in developing this feature
- [ ] No, I am not interested in developing this feature

**Comment by Elius94** [comment]
Yes! this is really important to do. Thanks!
I'm also working to a major release with plugins included as peer dep to prevent them to be carried with the package.

**Comment by Elius94** [comment]
Hey @mkubdev 

https://github.com/Elius94/react-photo-sphere-viewer/releases/tag/v5.0.0-psv5.7.1

Keep in mind this breaking change to the lib!!!

> [!IMPORTANT]
> Since v5.0.0-psv5.7.1, to use `<ReactPhotoSphereViewer />` you have to manually install the JS library `@photo-sphere-viewer/core`. This is a breaking change. The library is not included in the package anymore. You can install it using the command `npm install @photo-sphere-viewer/core` or `yarn add @photo-sphere-viewer/core`. I decided to remove the library from the package to reduce the size of the package and to avoid the need to update the package every time the original library is updated. In particular, from now on, to use a plugin or an adapter, you need to import it directly from the package. For example, to use the `MarkersPlugin` you need to import it from the package `import { MarkersPlugin } from '@photo-sphere-viewer/markers-plugin'`.

**Comment by mkubdev** [comment]
Hey @Elius94, i'm on it!
