### ISSUE TITLE
[Bug]:  WARNING: Multiple instances of Three.js being imported

### ISSUE THREAD

**Issue by rbsam176** [Elius94/react-photo-sphere-viewer#56]
### What happened?

Integrating one instance of React Photo Sphere Viewer shows a console warning: "WARNING: Multiple instances of Three.js being imported". The issue occurs in the sandbox demo linked in the docs (which I have also provided in this report)

### What should have happened?

I don't see why multiple instances should be imported, if this is a necessity could an explanation be added to the docs?

### Sandbox Link

https://codesandbox.io/p/sandbox/react-photo-sphere-viewer-playground-zd8nt8?file=%2Fsrc%2FApp.js

### Library Version

latest

### What operating system are you using?

Windows

### What browser are you using?

None

### Logs

 WARNING: Multiple instances of Three.js being imported.

### Interest to fix the bug

- [ ] I would like to fix this bug!

**Comment by Elius94** [comment]
This issue has been fixed in the new release v6.0.0 :)
