### ISSUE TITLE
[Bug]: Plugins are not working

### ISSUE THREAD

**Issue by SuhaibMaraqa** [Elius94/react-photo-sphere-viewer#64]
### What happened?

The markers plugin is not working in version 6.0.0, also I tried the compass plugin and it's not working. I provided the codesandbox playground

### What should have happened?

to show markers on the panorama

### Sandbox Link

https://codesandbox.io/p/sandbox/62hyg5

### Library Version

6.0.0

### What operating system are you using?

macOS

### What browser are you using?

Chrome

### Interest to fix the bug

- [ ] I would like to fix this bug!

**Comment by Elius94** [comment]
Hey!
![image](https://github.com/user-attachments/assets/839e7937-5ab3-4a58-bb92-45cd677ff2e3)

this is Chrome on Mac OS. it seems working
