### ISSUE TITLE
[Bug]: defaultZoomLvl only works with images in the public directory.

### ISSUE THREAD

**Issue by devinmarkley** [Elius94/react-photo-sphere-viewer#65]
### What happened?

defaultZoomLvl only works with images in the public directory.

### What should have happened?

The image should zoom to the default no matter how to is served.

### Code

`import React from "react";
import { ReactPhotoSphereViewer } from "react-photo-sphere-viewer";

function App() {
  const photoSphereRef = React.useRef();
  return (
    <div className="App">
      <ReactPhotoSphereViewer
        ref={photoSphereRef}
        /* defaultZoomLvl will only work with images in the public directory */
        src={"https://i.ibb.co/23KMzTN/GSAA5125.jpg"}
        defaultZoomLvl={0}
        hideNavbarButton={true}
        width={"100vw"}
        height={"100vh"}
        navbar={false}
      />
    </div>
  );
}

export default App;`

### Sandbox Link

https://codesandbox.io/p/github/devinmarkley/rps_example/main?workspaceId=ada4ce98-a807-4c56-b005-aabd6d57a5c0

### Library Version

"react-photo-sphere-viewer": "^6.0.0"
"@photo-sphere-viewer/core": "^5.9.0"

### What operating system are you using?

macOS

### What browser are you using?

Chrome

### Logs

Failed to parse source map from '/project/workspace/node_modules/react-photo-sphere-viewer/src/index.tsx' file: Error: ENOENT: no such file or directory, open '/project/workspace/node_modules/react-photo-sphere-viewer/src/index.tsx'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/react-photo-sphere-viewer/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/workspace/node_modules/react-photo-sphere-viewer/src/index.tsx' file: Error: ENOENT: no such file or directory, open '/project/workspace/node_modules/react-photo-sphere-viewer/src/index.tsx'

### Interest to fix the bug

- [ ] I would like to fix this bug!

**Comment by devinmarkley** [comment]
My issue is wrong. My images are not zoomed correctly because the EXIF in the 360-degree images GoPro seems to add many properties that throw off the library. Removing them using EXIF tool resolved the issue.

**Comment by Elius94** [comment]
Ok I'm glad to hear that it's ok
