### ISSUE TITLE
fullscreen does not seem to work on safari

### ISSUE THREAD

**Issue by tap2k** [Elius94/react-photo-sphere-viewer#8]
request full screen doesnt seem to work on safari. image is shown only in small size in top left corner. any fix?

**Comment by Elius94** [comment]
Ok, thanks. I have never tested it on Safari... I will provide to figure out. If you want, any help is welcome. I suppose that it's a CSS error. Can you try to find some hint using the developer console? Thanks

**Comment by tap2k** [comment]
Ive attached a screen shot below. It seems like the error is intermittent - the first one or two times it works, and then it reverts to this behavior. No further info from develop console, sorry!

![Screen Shot 2022-11-07 at 11 53 23 AM](https://user-images.githubusercontent.com/3065806/200368708-495e689c-b932-4086-aae6-61b32b9907a0.png)

**Comment by Elius94** [comment]
I will try this on a Apple PC asap. ;)

**Comment by mkubdev** [comment]
Hey :wave:

If I remember, Safari 9 is not handling  `width` percentage correctly.

**Comment by Elius94** [comment]
> 

Thanks a lot Maxime.
I tried this with an Apple computer of a friend of mine and it worked as expetted in full screen.
