### ISSUE TITLE
[Solved] Can't import the lib in next.js framework

### ISSUE THREAD

**Issue by mkubdev** [Elius94/react-photo-sphere-viewer#9]
## Description

First, thanks a lot for this lib. 🤘 I'm a big user of the original library by @mistic100, building on next.js with it.
I recently found your fork, and I was more than happy to see a react implementation. But unfortunately, I can't import it on next.js framework => `SyntaxError: Cannot use import statement outside a module`.

## Context

From a fresh nextjs 13 + TypeScript install, using this implementation :

1. `npx create-next-app@latest --ts test`
2. `cd test`
3. `npm i react-photo-sphere-viewer --save`
4. Add the library in `index.jsx` :

* src/pages/index.tsx
```jsx
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ReactPhotoSphereViewer } from 'react-photo-sphere-viewer';
import { useRef } from 'react';

export default function Home() {
  const photoSphereRef: any = useRef();

  const handleClick = () => {
    photoSphereRef.current.animate({
      latitude: 0,
      longitude: 0,
      zoom: 55,
      speed: '10rpm',
    });
  };

  return (
    <div className="App">
      <ReactPhotoSphereViewer
        ref={photoSphereRef}
        src="Test_Pano.jpg"
        height={'100vh'}
        width={'100%'}
        onClick={handleClick}
      ></ReactPhotoSphereViewer>
    </div>
  );
}
```

* tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```
6. `npm run dev`
7. Throwing error: `SyntaxError: Cannot use import statement outside a module` :
![image](https://user-images.githubusercontent.com/50140834/200814451-f279936f-8d58-4698-93fb-570c4d4b75f0.png)

* Full error:
```bash
error - /home/mkubik/dev/10.labs/test/node_modules/react-photo-sphere-viewer/dist/index.js:1
import React, { forwardRef, createRef, useState, useEffect, useImperativeHandle } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module      
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)     
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)   
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)    at require (node:internal/modules/cjs/helpers:102:18)      
    at Object.react-photo-sphere-viewer (/home/mkubik/dev/10.labs/test/.next/server/pages/index.js:42:18)
    at __webpack_require__ (/home/mkubik/dev/10.labs/test/.next/server/webpack-runtime.js:33:42) {
  page: '/'
}
```

## What I tried

* Everything from [here](https://stackoverflow.com/questions/58211880/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-import)

* Next.js Dynamic import: 

```js
// import { ReactPhotoSphereViewer } from 'react-photo-sphere-viewer';

const ReactPhotoSphereViewer = dynamic(
  () => import('react-photo-sphere-viewer'),
  {
    ssr: false,
  }
);
```

But a new error appears:
![image](https://user-images.githubusercontent.com/50140834/200845561-068fd903-df02-4b72-a4ee-aaa9a9b58b41.png)

* I also tried to add it like above (## Context) but with **VanillaJS Next.js** install, same results.
* Also tried next.js 12, same results.

## Problems

I'm not sure of the problem here, but if I achieve to find it, I'll open a PR to fix it. I forked and will check ASAP.

Again, this lib wrapper is a super idea, thanks a lot! 🚀

**Comment by Elius94** [comment]
Hi Maxime! thanks a lot for the issue,
Another user had this trouble with my lib and Next.js and he solved with this issue: https://github.com/Elius94/react-photo-sphere-viewer/issues/7

Please feel free to fire a PR to help this project rise.
I will also try to figure it out by myself in the next days.
Thanks

**Comment by mkubdev** [comment]
> Another user had this trouble with my lib and Next.js and he solved with this issue: https://github.com/Elius94/react-photo-sphere-viewer/issues/7

Yeah, I came back here just to post a solution:

```js
const ReactPhotoSphereViewer = dynamic(
  () =>
    import('react-photo-sphere-viewer').then(
      (mod) => mod.ReactPhotoSphereViewer
    ),
  {
    ssr: false,
  }
);
```

So same solution as #7 !
> I will also try to figure it out by myself in the next days.

I keep you in touch if I can improve the nextjs implementation in the next days too.

Have a nice day :wave:

**Comment by Elius94** [comment]
Super!!! Thanks a lot! Let me know :D
